# Generated by Django 3.1.6 on 2021-02-13 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='number',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
